# Ex1 - Filtering and Sorting Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [2]:
import pandas as pd 
import numpy as np

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

### Step 3. Assign it to a variable called chipo.

In [92]:
url="https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv"

chipo = pd.read_table("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv")
chipo['item_name']

0                Chips and Fresh Tomato Salsa
1                                        Izze
2                            Nantucket Nectar
3       Chips and Tomatillo-Green Chili Salsa
4                                Chicken Bowl
                        ...
4617                            Steak Burrito
4618                            Steak Burrito
4619                       Chicken Salad Bowl
4620                       Chicken Salad Bowl
4621                       Chicken Salad Bowl
Name: item_name, Length: 4622, dtype: object

### Step 4. How many products cost more than $10.00?

In [93]:
chipo['item_price'] = chipo['item_price'].str.replace("$", "").astype(float)
bin = chipo.drop_duplicates(['item_name', 'quantity', 'choice_description'])

bin1 = bin[(bin['quantity'] == 1) & (bin['item_price'] > 10)]
bin1

<ipython-input-93-d25864635852>:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  chipo['item_price'] = chipo['item_price'].str.replace("$", "").astype(float)

,order_id,quantity,item_name,choice_description,item_price
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",10.98
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.75
13,7,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
23,12,1,Chicken Burrito,"[[Tomatillo-Green Chili Salsa (Medium), Tomati...",10.98
39,19,1,Barbacoa Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",11.75
...,...,...,...,...,...
4593,1825,1,Carnitas Bowl,"[Roasted Chili Corn Salsa, [Rice, Sour Cream, ...",11.75
4594,1825,1,Barbacoa Bowl,"[Roasted Chili Corn Salsa, [Pinto Beans, Sour ...",11.75
4607,1829,1,Steak Burrito,"[Tomatillo Green Chili Salsa, [Rice, Cheese, S...",11.75
4610,1830,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4611,1830,1,Veggie Burrito,"[Tomatillo Green Chili Salsa, [Rice, Fajita Ve...",11.25

715

In [51]:
# clean the item_price column and transform it in a float
chipo['item_price'] = chipo['item_price'].str.replace("$", "").astype(float)

# reassign the column with the cleaned prices
chipo = chipo.drop_duplicates(['item_name', 'quantity'])

# delete the duplicates in item_name and quantity


# sleect only the products with quantity equals to 1
chipo['more10'] = chipo['item_price'] / chipo['quantity']
len(chipo[chipo['more10'] > 10])

<ipython-input-51-41fb508a374a>:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  chipo['item_price'] = chipo['item_price'].str.replace("$", "").astype(float)
<ipython-input-51-41fb508a374a>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chipo['more10'] = chipo['item_price'] / chipo['quantity']

18

### Step 5. What is the price of each item? 
###### print a data frame with only two columns item_name and item_price

In [94]:
chipo = chipo.drop_duplicates(['item_name','quantity'])
a = chipo[chipo['quantity'] == 1]
a = a[['item_name', 'item_price']]
a.sort_values('item_price', ascending=False).head(20)

                  item_name  item_price
606        Steak Salad Bowl       11.89
1229    Barbacoa Salad Bowl       11.89
1132    Carnitas Salad Bowl       11.89
7             Steak Burrito       11.75
168   Barbacoa Crispy Tacos       11.75
39            Barbacoa Bowl       11.75
738       Veggie Soft Tacos       11.25
186       Veggie Salad Bowl       11.25
62              Veggie Bowl       11.25
57           Veggie Burrito       11.25
250           Chicken Salad       10.98
5              Chicken Bowl       10.98
8          Steak Soft Tacos        9.25
554   Carnitas Crispy Tacos        9.25
237     Carnitas Soft Tacos        9.25
56      Barbacoa Soft Tacos        9.25
92       Steak Crispy Tacos        9.25
664             Steak Salad        8.99
54               Steak Bowl        8.99
3750         Carnitas Salad        8.99

In [ ]:
# delete the duplicates in item_name and quantity


# select only the products with quantity equals to 1


# select only the item_name and item_price columns


# sort the values from the most to less expensive

                  item_name  item_price
606        Steak Salad Bowl       11.89
1229    Barbacoa Salad Bowl       11.89
1132    Carnitas Salad Bowl       11.89
7             Steak Burrito       11.75
168   Barbacoa Crispy Tacos       11.75
39            Barbacoa Bowl       11.75
738       Veggie Soft Tacos       11.25
186       Veggie Salad Bowl       11.25
62              Veggie Bowl       11.25
57           Veggie Burrito       11.25
250           Chicken Salad       10.98
5              Chicken Bowl       10.98
8          Steak Soft Tacos        9.25
554   Carnitas Crispy Tacos        9.25
237     Carnitas Soft Tacos        9.25
56      Barbacoa Soft Tacos        9.25
92       Steak Crispy Tacos        9.25
664             Steak Salad        8.99
54               Steak Bowl        8.99
3750         Carnitas Salad        8.99

### Step 6. Sort by the name of the item

In [48]:
chipo.sort_values('item_name')

,order_id,quantity,item_name,choice_description,item_price
3389,1360,2,6 Pack Soft Drink,[Diet Coke],$12.98
341,148,1,6 Pack Soft Drink,[Diet Coke],$6.49
1849,749,1,6 Pack Soft Drink,[Coke],$6.49
1860,754,1,6 Pack Soft Drink,[Diet Coke],$6.49
2713,1076,1,6 Pack Soft Drink,[Coke],$6.49
...,...,...,...,...,...
2384,948,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$8.75
781,322,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Black Beans, Cheese, Sou...",$8.75
2851,1132,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",$8.49
1699,688,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$11.25
1395,567,1,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",$8.49

In [ ]:


# OR

,order_id,quantity,item_name,choice_description,item_price
3389,1360,2,6 Pack Soft Drink,[Diet Coke],12.98
341,148,1,6 Pack Soft Drink,[Diet Coke],6.49
1849,749,1,6 Pack Soft Drink,[Coke],6.49
1860,754,1,6 Pack Soft Drink,[Diet Coke],6.49
2713,1076,1,6 Pack Soft Drink,[Coke],6.49
3422,1373,1,6 Pack Soft Drink,[Coke],6.49
553,230,1,6 Pack Soft Drink,[Diet Coke],6.49
1916,774,1,6 Pack Soft Drink,[Diet Coke],6.49
1922,776,1,6 Pack Soft Drink,[Coke],6.49
1937,784,1,6 Pack Soft Drink,[Diet Coke],6.49
3836,1537,1,6 Pack Soft Drink,[Coke],6.49
298,129,1,6 Pack Soft Drink,[Sprite],6.49
1976,798,1,6 Pack Soft Drink,[Diet Coke],6.49
1167,481,1,6 Pack Soft Drink,[Coke],6.49
3875,1554,1,6 Pack Soft Drink,[Diet Coke],6.49
1124,465,1,6 Pack Soft Drink,[Coke],6.49
3886,1558,1,6 Pack Soft Drink,[Diet Coke],6.49
2108,849,1,6 Pack Soft Drink,[Coke],6.49
3010,1196,1,6 Pack Soft Drink,[Diet Coke],6.49
4535,1803,1,6 Pack Soft Drink,[Lemonade],6.49
4169,1664,1,6 Pack Soft Drink,[Diet Coke],6.49
4174,1666,1,6 Pack Soft Drink,[Coke],6.49
4527,1800,1,6 Pack Soft Drink,[Diet Coke],6.49
4522,1798,1,6 Pack Soft Drink,[Diet Coke],6.49
3806,1525,1,6 Pack Soft Drink,[Sprite],6.49
2389,949,1,6 Pack Soft Drink,[Coke],6.49
3132,1248,1,6 Pack Soft Drink,[Diet Coke],6.49
3141,1253,1,6 Pack Soft Drink,[Lemonade],6.49
639,264,1,6 Pack Soft Drink,[Diet Coke],6.49
1026,422,1,6 Pack Soft Drink,[Sprite],6.49
...,...,...,...,...,...
2996,1192,1,Veggie Salad,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",8.49
3163,1263,1,Veggie Salad,"[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...",8.49
4084,1635,1,Veggie Salad,"[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...",8.49
1694,686,1,Veggie Salad,"[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...",8.49
2756,1094,1,Veggie Salad,"[[Tomatillo-Green Chili Salsa (Medium), Roaste...",8.49
4201,1677,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Black...",11.25
1884,760,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
455,195,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
3223,1289,1,Veggie Salad Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.25
2223,896,1,Veggie Salad Bowl,"[Roasted Chili Corn Salsa, Fajita Vegetables]",8.75
2269,913,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",8.75
4541,1805,1,Veggie Salad Bowl,"[Tomatillo Green Chili Salsa, [Fajita Vegetabl...",8.75
3293,1321,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",8.75
186,83,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
960,394,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75
1316,536,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",8.75
2156,869,1,Veggie Salad Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.25
4261,1700,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
295,128,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",11.25
4573,1818,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75
2683,1066,1,Veggie Salad Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75
496,207,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Rice, Lettuce, Guacamole...",11.25
4109,1646,1,Veggie Salad Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.25
738,304,1,Veggie Soft Tacos,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.25
3889,1559,2,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",16.98
2384,948,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75
781,322,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Black Beans, Cheese, Sou...",8.75
2851,1132,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",8.49
1699,688,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
1395,567,1,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",8.49

### Step 7. What was the quantity of the most expensive item ordered?

In [60]:
chipo.sort_values('item_price', ascending=False).head(1)

,order_id,quantity,item_name,choice_description,item_price
2624,1042,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Black Beans, Sour Cream,...",$9.39

,order_id,quantity,item_name,choice_description,item_price
3598,1443,15,Chips and Fresh Tomato Salsa,NaN,44.25

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [69]:
len(chipo[chipo['item_name'] == "Veggie Salad Bowl"])

18

In [68]:
chipo.value_counts('item_name')

item_name
Chicken Bowl                             726
Chicken Burrito                          553
Chips and Guacamole                      479
Steak Burrito                            368
Canned Soft Drink                        301
Steak Bowl                               211
Chips                                    211
Bottled Water                            162
Chicken Soft Tacos                       115
Chicken Salad Bowl                       110
Chips and Fresh Tomato Salsa             110
Canned Soda                              104
Side of Chips                            101
Veggie Burrito                            95
Barbacoa Burrito                          91
Veggie Bowl                               85
Carnitas Bowl                             68
Barbacoa Bowl                             66
Carnitas Burrito                          59
Steak Soft Tacos                          55
6 Pack Soft Drink                         54
Chips and Tomatillo Red Chili Salsa       48
Chicken Crispy Tacos                      47
Chips and Tomatillo Green Chili Salsa     43
Carnitas Soft Tacos                       40
Steak Crispy Tacos                        35
Chips and Tomatillo-Green Chili Salsa     31
Steak Salad Bowl                          29
Nantucket Nectar                          27
Barbacoa Soft Tacos                       25
Chips and Roasted Chili Corn Salsa        22
Chips and Tomatillo-Red Chili Salsa       20
Izze                                      20
Veggie Salad Bowl                         18
Chips and Roasted Chili-Corn Salsa        18
Barbacoa Crispy Tacos                     11
Barbacoa Salad Bowl                       10
Chicken Salad                              9
Carnitas Crispy Tacos                      7
Veggie Soft Tacos                          7
Burrito                                    6
Veggie Salad                               6
Carnitas Salad Bowl                        6
Steak Salad                                4
Bowl                                       2
Salad                                      2
Crispy Tacos                               2
Chips and Mild Fresh Tomato Salsa          1
Carnitas Salad                             1
Veggie Crispy Tacos                        1
dtype: int64

In [ ]:
len(chipo[chipo['item_name'] == "Veggie Salad Bowl"])

18

### Step 9. How many times did someone order more than one Canned Soda?

In [81]:
b = chipo[chipo['item_name'] == "Canned Soda"]
len(b[b['quantity'] != 1])

20